services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: av-scheduler
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_URL: http://localhost:8000
      HOME: /tmp
      NPM_CONFIG_CACHE: /tmp/.npm
    extra_hosts:
      - "host.docker.internal:host-gateway"
